In [1]:
pg_uri = 'postgresql://postgres:J*5_dnaV1HrD%3C5)CN2B%23CmW2%5D%5DT.@prod-cluster.cluster-ca6mb0dddnzs.us-east-2.rds.amazonaws.com/postgres?application_name=prod_be'
dataset_id = '71b2cd90-2431-11ef-84ed-5a40921d4b2c'

import polars as pl

issues = pl.read_database_uri(
    f"select * from image_issues where dataset_id = '{dataset_id}'",
    pg_uri
)

issues_types = pl.read_database_uri(
    'select * from issue_type',
    pg_uri
)

issues = issues.join(issues_types, left_on='type_id', right_on='id')

image_issues = issues.filter(pl.col('cause').is_null())
image_issues = image_issues.select(
    'image_id',
    issues=pl.struct(
        'confidence',
        'description',
        issue_type='name'
    )
)
image_issues = image_issues.group_by('image_id').all()

In [2]:
import polars as pl

tables_query = """
SELECT table_schema, table_name
FROM information_schema.tables
WHERE table_type = 'BASE TABLE'
  AND table_name NOT LIKE 'flat_similarity%'
  AND table_name NOT LIKE 'image_vector%'
  AND table_schema = 'public'
ORDER BY table_schema, table_name
"""

# Read the list of tables from the database
tables = pl.read_database_uri(
    tables_query,
    pg_uri
)

In [3]:
tables.to_pandas()

   table_schema                      table_name
0        public                          access
1        public                        api_keys
2        public                        clusters
3        public                  dataset_issues
4        public                        datasets
5        public               db_schema_version
6        public                          events
7        public                     export_task
8        public                       flow_runs
9        public                    image_issues
10       public        image_similarity_mapping
11       public                          images
12       public              images_to_clusters
13       public   images_to_similarity_clusters
14       public                      issue_type
15       public                label_categories
16       public                          labels
17       public               media_to_captions
18       public                   media_to_tags
19       public       object_similarity_mapping
20       public                         objects
21       public               objects_to_images
22       public  objects_to_similarity_clusters
23       public          query_vector_embedding
24       public             similarity_clusters
25       public                            tags
26       public                           users

In [5]:
tables_query = """
SELECT * FROM image_issues 
WHERE dataset_id = '71b2cd90-2431-11ef-84ed-5a40921d4b2c'
LIMIT 10
"""

# Read the list of tables from the database
tables = pl.read_database_uri(
    tables_query,
    pg_uri
)

tables.to_pandas()

,id,type_id,image_id,dataset_id,description,cause,confidence,issue_subject_id
0,2419023d-7b0f-4143-9c6c-3470c87ad7f9,2,d46850e4-b2f3-4c34-b9c3-9d44cc6d2792,71b2cd90-2431-11ef-84ed-5a40921d4b2c,None,None,0.980000,None
1,82857009-def0-4476-b70c-6a5e0fe7bc84,2,83d937fa-5523-42b0-aefa-89ea00449f3f,71b2cd90-2431-11ef-84ed-5a40921d4b2c,None,None,0.980000,None
2,51a5351b-a7a9-4819-9a04-ffc22e061f0e,2,916447e7-00ca-4a52-8d55-d96a93e1cfd6,71b2cd90-2431-11ef-84ed-5a40921d4b2c,None,None,0.980000,None
3,0218bd9a-1a50-46d6-83e9-3d37076a4237,2,c6f1e92d-77e4-4b17-af9f-42cff6fbaa13,71b2cd90-2431-11ef-84ed-5a40921d4b2c,None,None,0.912505,None
4,dcc16c2b-747d-45a9-9adf-06e7759c4901,2,4b4e97a3-6150-4237-af93-37b65aa8c7d7,71b2cd90-2431-11ef-84ed-5a40921d4b2c,None,None,0.980000,None
5,d16341ef-9de8-4a41-9178-a0e2966b3bb8,2,d6b24482-bc95-4c32-88a6-69d910b97872,71b2cd90-2431-11ef-84ed-5a40921d4b2c,None,None,0.980000,None
6,79a53795-eb5b-4b30-adbd-190d51264dd9,2,39abc0d9-6091-4e9c-a62c-5e0ef5731ddf,71b2cd90-2431-11ef-84ed-5a40921d4b2c,None,None,0.980000,None
7,524f804b-3544-4a61-8b4a-a14a24aa5411,2,8e150d6f-b362-4eb4-ab0c-0bbf96c25fe0,71b2cd90-2431-11ef-84ed-5a40921d4b2c,None,None,0.980000,None
8,015ea2db-faeb-4569-87c9-da06b8d6c9fa,2,dfd69c58-4f43-4d32-a4da-b23be90d4a83,71b2cd90-2431-11ef-84ed-5a40921d4b2c,None,None,0.980000,None
9,115c3f85-ffaf-41f3-b312-5230f990896a,2,7d0a1e4e-d0da-4f20-b754-2c5dbeff0043,71b2cd90-2431-11ef-84ed-5a40921d4b2c,None,None,0.980000,None